import {
  IconLayoutDashboard,
  IconCommand,
  IconLogin,
  IconX,
  IconShoppingBag,
  IconLoader2,
  IconLayoutKanban,
  IconChevronLeft,
  IconChevronRight,
  IconTrash,
  IconUserX,
  IconFileText,
  IconFile,
  IconUserEdit,
  IconUserCircle,
  IconPhoto,
  IconSettings,
  IconCreditCard,
  IconDotsVertical,
  IconPlus,
  IconAlertTriangle,
  IconUser,
  IconArrowRight,
  IconHelpCircle,
  IconPizza,
  IconSun,
  IconMoon,
  IconDeviceLaptop,
  IconBrandGithub,
  IconBrandTwitter,
  IconCheck,
  IconSchool,
  IconUsers,
  IconBriefcase,
  IconClipboardList,
  IconBuildingBank,
  IconHome,
  IconBus,
  IconBook,
  IconToolsKitchen2,
  IconHeartbeat,
  IconTrophy,
  IconAward,
  IconMessage,
  IconCalendar,
  IconCalendarOff,
  IconGavel,
  IconPackage,
  IconTool,
  IconUserPlus,
  IconBuildingStore,
  IconClipboardCheck,
  IconUserCheck,
  IconBed,
  IconMap,
  IconCash,
  IconWallet,
  IconCategory,
  IconMenu,
  IconShoppingCart,
  IconMedal,
  IconAddressBook,
  IconNews,
  IconSpeakerphone,
  IconBell,
  IconFolder,
  IconBuilding,
  IconDots,
  IconEdit,
  IconAdjustmentsHorizontal
} from '@tabler/icons-react';

export const Icons = {
  // Existing icons
  dashboard: IconLayoutDashboard,
  schools: IconBuilding,
  logo: IconCommand,
  login: IconLogin,
  close: IconX,
  product: IconShoppingBag,
  spinner: IconLoader2,
  kanban: IconLayoutKanban,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  trash: IconTrash,
  employee: IconUserX,
  post: IconFileText,
  page: IconFile,
  userPen: IconUserEdit,
  user2: IconUserCircle,
  media: IconPhoto,
  settings: IconSettings,
  billing: IconCreditCard,
  ellipsis: IconDotsVertical,
  add: IconPlus,
  warning: IconAlertTriangle,
  user: IconUser,
  arrowRight: IconArrowRight,
  help: IconHelpCircle,
  pizza: IconPizza,
  sun: IconSun,
  moon: IconMoon,
  laptop: IconDeviceLaptop,
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  check: IconCheck,

  // Main categories
  academic: IconSchool,
  students: IconUsers,
  staff: IconBriefcase,
  examinations: IconClipboardList,
  finance: IconBuildingBank,
  hostel: IconHome,
  transport: IconBus,
  library: IconBook,
  cafeteria: IconToolsKitchen2,
  health: IconHeartbeat,
  activities: IconTrophy,
  certificates: IconAward,
  communications: IconMessage,
  events: IconCalendar,
  leave: IconCalendarOff,
  disciplinary: IconGavel,
  inventory: IconPackage,
  maintenance: IconTool,
  visitors: IconUserPlus,
  vendors: IconBuildingStore,
  purchaseOrders: IconClipboardCheck,
  system: IconSettings,

  // Additional icons used in sub-items
  clipboardCheck: IconClipboardCheck,
  userCheck: IconUserCheck,
  bed: IconBed,
  edit: IconEdit,
  map: IconMap,
  cash: IconCash,
  wallet: IconWallet,
  category: IconCategory,
  menu: IconMenu,
  shoppingCart: IconShoppingCart,
  medal: IconMedal,
  addressBook: IconAddressBook,
  news: IconNews,
  bullhorn: IconSpeakerphone,
  bell: IconBell,
  plus: IconPlus,
  folder: IconFolder,
  calendar: IconCalendar,
  heartbeat: IconHeartbeat,
  moreHorizontal: IconDots,
  slidersHorizontal: IconAdjustmentsHorizontal
};
